appium_host: "127.0.0.1"
adb_host: "127.0.0.1"
appium_auto_run: "False"
app_auto_install: "False"
capabilities_location: "resources/capabilities.json"
test_data_location: "None"
android_page_objects_package: "None"
ios_page_objects_package: "None"
logger_name: "test_logs.log"
app_path: "~/Downloads/test.apk"