appium_host_url:http://localhost
appium_auto_run:false
app_auto_install:false
capabilities_location:None
test_data_location:None
android_page_objects_package:None
ios_page_objects_package:None
platform:ANDROID
ports:4723
app_path:None
